[package]
name = "amll-player"
version = "0.0.0"
description = "AMLL Player"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc", features = [ "devtools"] }
tauri-plugin-dialog = "2.0.0-rc"

base64 = "^0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-tungstenite = { version = "0.23.0", features = ["async-std-runtime"] }
async-std = "1.12.0"
anyhow = "1.0.72"
futures = "0.3.28"
symphonia = { version = "^0.5", features = ["all", "opt-simd"] }
ws-protocol = { path = "../../ws-protocol" }
amll-player-core = { path = "../../player-core" }
tokio = { version = "1.35.0", features = ["time", "macros", "sync", "rt", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
debug = false
strip = true
