
"$schema" = "../gen/schemas/desktop-schema.json"

identifier = "desktop-capability"
local = true
windows = ["main"]
platforms = ["macOS", "windows", "linux"]

[[permissions]]
identifier = "updater:default"
[[permissions]]
identifier = "global-shortcut:default"
[[permissions]]
identifier = "global-shortcut:allow-is-registered"
[[permissions]]
identifier = "global-shortcut:allow-register"
[[permissions]]
identifier = "global-shortcut:allow-unregister"
